// const API_URL = "https://v3.football.api-sports.io/players?id=1100&season=2023";
// const API_KEY = process.env.API_KEY!;

export default async function getPlayerStatics() {
  // const request = new Request ( API_URL, {
  //   headers : {
  //     "x-apisports-key" : API_KEY
  //   }
  // })

  // const response = await fetch(request);

  // const data = await response.json();

  const data = [
    {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 39,
        name: "Premier League",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/39.png",
        flag: "https://media.api-sports.io/flags/gb-eng.svg",
        season: 2023,
      },
      games: {
        appearences: 32,
        lineups: 30,
        minutes: 2556,
        number: null,
        position: "Attacker",
        rating: "7.361290",
        captain: false,
      },
      substitutes: { in: 2, out: null, bench: null },
      shots: { total: 98, on: 59 },
      goals: { total: 27, conceded: 0, assists: 5, saves: null },
      passes: { total: 381, key: 29, accuracy: null },
      tackles: { total: 6, blocks: 1, interceptions: 2 },
      duels: { total: 184, won: 88 },
      dribbles: { attempts: 28, success: 12, past: null },
      fouls: { drawn: 31, committed: 18 },
      cards: { yellow: 1, yellowred: null, red: 0 },
      penalty: { won: null, commited: null, scored: 7, missed: 1, saved: null },
    },
    {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 528,
        name: "Community Shield",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/528.png",
        flag: "https://media.api-sports.io/flags/gb-eng.svg",
        season: 2023,
      },
      games: {
        appearences: 1,
        lineups: 1,
        minutes: 64,
        number: null,
        position: "Attacker",
        rating: "6.200000",
        captain: false,
      },
      substitutes: { in: 0, out: null, bench: null },
      shots: { total: null, on: null },
      goals: { total: null, conceded: 0, assists: null, saves: null },
      passes: { total: 9, key: null, accuracy: null },
      tackles: { total: null, blocks: null, interceptions: null },
      duels: { total: 4, won: 2 },
      dribbles: { attempts: 1, success: null, past: null },
      fouls: { drawn: null, committed: 1 },
      cards: { yellow: 0, yellowred: null, red: 0 },
      penalty: { won: null, commited: null, scored: 0, missed: 0, saved: null },
    },
    {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 45,
        name: "FA Cup",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/45.png",
        flag: "https://media.api-sports.io/flags/gb-eng.svg",
        season: 2023,
      },
      games: {
        appearences: 3,
        lineups: 3,
        minutes: 254,
        number: null,
        position: "Attacker",
        rating: "6.600000",
        captain: false,
      },
      substitutes: { in: 0, out: 2, bench: 0 },
      shots: { total: 4, on: null },
      goals: { total: 5, conceded: 0, assists: 0, saves: null },
      passes: { total: 32, key: 1, accuracy: null },
      tackles: { total: null, blocks: null, interceptions: null },
      duels: { total: 21, won: 6 },
      dribbles: { attempts: 4, success: 1, past: null },
      fouls: { drawn: 3, committed: 3 },
      cards: { yellow: 0, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 0, missed: 0, saved: null },
    },
    {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 48,
        name: "League Cup",
        country: "England",
        logo: "https://media.api-sports.io/football/leagues/48.png",
        flag: "https://media.api-sports.io/flags/gb-eng.svg",
        season: 2023,
      },
      games: {
        appearences: 0,
        lineups: 0,
        minutes: 0,
        number: null,
        position: "Attacker",
        rating: null,
        captain: false,
      },
      substitutes: { in: 0, out: 0, bench: 1 },
      shots: { total: null, on: null },
      goals: { total: 0, conceded: 0, assists: null, saves: null },
      passes: { total: null, key: null, accuracy: null },
      tackles: { total: null, blocks: null, interceptions: null },
      duels: { total: null, won: null },
      dribbles: { attempts: null, success: null, past: null },
      fouls: { drawn: null, committed: null },
      cards: { yellow: 0, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 0, missed: 0, saved: null },
    },
    {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 2,
        name: "UEFA Champions League",
        country: "World",
        logo: "https://media.api-sports.io/football/leagues/2.png",
        flag: null,
        season: 2023,
      },
      games: {
        appearences: 9,
        lineups: 9,
        minutes: 779,
        number: null,
        position: "Attacker",
        rating: "7.155555",
        captain: false,
      },
      substitutes: { in: 0, out: 4, bench: 0 },
      shots: { total: 38, on: 22 },
      goals: { total: 6, conceded: 0, assists: 1, saves: null },
      passes: { total: 88, key: 8, accuracy: null },
      tackles: { total: 5, blocks: null, interceptions: null },
      duels: { total: 42, won: 23 },
      dribbles: { attempts: 9, success: 3, past: null },
      fouls: { drawn: 4, committed: 4 },
      cards: { yellow: 0, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 2, missed: 0, saved: null },
    },
    {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 531,
        name: "UEFA Super Cup",
        country: "World",
        logo: "https://media.api-sports.io/football/leagues/531.png",
        flag: null,
        season: 2023,
      },
      games: {
        appearences: 1,
        lineups: 1,
        minutes: 90,
        number: null,
        position: "Attacker",
        rating: null,
        captain: false,
      },
      substitutes: { in: 0, out: 0, bench: 0 },
      shots: { total: null, on: null },
      goals: { total: 0, conceded: null, assists: null, saves: null },
      passes: { total: null, key: null, accuracy: null },
      tackles: { total: null, blocks: null, interceptions: null },
      duels: { total: null, won: null },
      dribbles: { attempts: null, success: null, past: null },
      fouls: { drawn: null, committed: null },
      cards: { yellow: 0, yellowred: 0, red: 0 },
      penalty: {
        won: null,
        commited: null,
        scored: null,
        missed: null,
        saved: null,
      },
    },
    {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: null,
        name: "FIFA Intercontinental Cup",
        country: null,
        logo: null,
        flag: null,
        season: 2023,
      },
      games: {
        appearences: 0,
        lineups: 0,
        minutes: 0,
        number: null,
        position: "Attacker",
        rating: null,
        captain: false,
      },
      substitutes: { in: 0, out: 0, bench: 0 },
      shots: { total: null, on: null },
      goals: { total: 0, conceded: null, assists: null, saves: null },
      passes: { total: null, key: null, accuracy: null },
      tackles: { total: null, blocks: null, interceptions: null },
      duels: { total: null, won: null },
      dribbles: { attempts: null, success: null, past: null },
      fouls: { drawn: null, committed: null },
      cards: { yellow: 0, yellowred: 0, red: 0 },
      penalty: {
        won: null,
        commited: null,
        scored: null,
        missed: null,
        saved: null,
      },
    },
    {
      team: {
        id: 50,
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      league: {
        id: 667,
        name: "Friendlies Clubs",
        country: "World",
        logo: "https://media.api-sports.io/football/leagues/667.png",
        flag: null,
        season: 2023,
      },
      games: {
        appearences: 2,
        lineups: 1,
        minutes: 99,
        number: null,
        position: "Attacker",
        rating: null,
        captain: false,
      },
      substitutes: { in: 1, out: 1, bench: 1 },
      shots: { total: null, on: null },
      goals: { total: 0, conceded: null, assists: null, saves: null },
      passes: { total: null, key: null, accuracy: null },
      tackles: { total: null, blocks: null, interceptions: null },
      duels: { total: null, won: null },
      dribbles: { attempts: null, success: null, past: null },
      fouls: { drawn: null, committed: null },
      cards: { yellow: 0, yellowred: 0, red: 0 },
      penalty: {
        won: null,
        commited: null,
        scored: null,
        missed: null,
        saved: null,
      },
    },
    {
      team: {
        id: 1090,
        name: "Norway",
        logo: "https://media.api-sports.io/football/teams/1090.png",
      },
      league: {
        id: 960,
        name: "Euro Championship - Qualification",
        country: "World",
        logo: "https://media.api-sports.io/football/leagues/960.png",
        flag: null,
        season: 2023,
      },
      games: {
        appearences: 5,
        lineups: 5,
        minutes: 428,
        number: null,
        position: "Attacker",
        rating: "7.480000",
        captain: false,
      },
      substitutes: { in: 0, out: 3, bench: 0 },
      shots: { total: 10, on: 9 },
      goals: { total: 6, conceded: 0, assists: 1, saves: null },
      passes: { total: 47, key: 3, accuracy: null },
      tackles: { total: null, blocks: null, interceptions: null },
      duels: { total: 29, won: 12 },
      dribbles: { attempts: 7, success: null, past: null },
      fouls: { drawn: 3, committed: 3 },
      cards: { yellow: 0, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 2, missed: 0, saved: null },
    },
    {
      team: {
        id: 1090,
        name: "Norway",
        logo: "https://media.api-sports.io/football/teams/1090.png",
      },
      league: {
        id: 10,
        name: "Friendlies",
        country: "World",
        logo: "https://media.api-sports.io/football/leagues/10.png",
        flag: null,
        season: 2023,
      },
      games: {
        appearences: 1,
        lineups: 0,
        minutes: 44,
        number: null,
        position: "Attacker",
        rating: "6.300000",
        captain: false,
      },
      substitutes: { in: 1, out: 0, bench: 2 },
      shots: { total: 1, on: null },
      goals: { total: 0, conceded: 0, assists: null, saves: null },
      passes: { total: 10, key: null, accuracy: null },
      tackles: { total: null, blocks: null, interceptions: null },
      duels: { total: 1, won: 1 },
      dribbles: { attempts: 1, success: 1, past: null },
      fouls: { drawn: null, committed: null },
      cards: { yellow: 0, yellowred: 0, red: 0 },
      penalty: { won: null, commited: null, scored: 0, missed: 0, saved: null },
    },
  ];

  return data;
}
